builders:
  frx_generator:
    import: "package:frx_generator/builder.dart"
    builder_factories: ["frxBuilder"]
    build_extensions: {".dart": ["*.frx.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen:combining_builder"]
    required_inputs: [".freezed.dart"]  # Đảm bảo freezed chạy trước