name: frx_generator
description: A lightweight extension generator for Freezed models in Dart.
version: 0.0.1
repository: https://github.com/cogivn/frx.git
documentation: https://github.com/cogivn/frx.git
homepage: https://github.com/cogivn/frx.git
issue_tracker: https://github.com/cogivn/frx.git/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  analyzer: '>=5.13.0 <8.0.0'
  build: ^2.4.2
  build_config: ^1.1.2
  source_gen: '>=1.0.0 <3.0.0'
  frx_annotation: 
    path: ../frx_annotation
  freezed_annotation: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.24.3
  source_gen_test: ^1.0.6
  build_test: ^2.2.0
  build_runner: ^2.4.6