name: frx_generator
description: Code generator for frx_annotation package that generates pattern matching methods for union types in Dart
version: 1.0.5
homepage: https://github.com/cogivn/frx
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: '>=5.13.0 <8.0.0'
  build: ^2.4.1
  source_gen: '>=1.0.0 <3.0.0'
  frx_annotation: ^1.0.2
  source_helper: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  source_gen_test: ^1.0.6
  build_test: ^2.2.0
  build_runner: ^2.4.6

topics:
  - codegen
  - pattern-matching
  - union-types
  - generator

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: