name: frx_annotation
description: Annotations for frx_generator package that enables pattern matching for union types in Dart
version: 1.0.2
homepage: https://github.com/cogivn/frx
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

# Package metadata
topics:
  - codegen
  - pattern-matching
  - union-types
